.TH "Serial_Communication" 3 "Thu Feb 20 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serial_Communication
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForm1\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
