.TH "Serial_Communication.Form1" 3 "Thu Feb 20 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serial_Communication.Form1
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm1\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Serial_Communication\&.Form1\&.Form1 ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "override void Serial_Communication\&.Form1\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
